---
title: "Football Events: Top Players"
author: "Jens Laufer"
date: "01/03/2018"
output:
  prettydoc::html_pretty:
    toc: true
    theme: architect


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=15, fig.height=10, echo = TRUE, message = TRUE, warning = FALSE)
```

```{r}
library(tidyverse)
```

```{r}
root <-  '../data'

data.zip.file <-  paste(root, '/events.zip', sep='')

events.file <-  paste(root, '/events.csv', sep='')
ginf.file <-  paste(root, '/ginf.csv', sep='')


if(!file.exists(events.file)){
    res <- tryCatch(download.file('https://s3.eu-central-1.amazonaws.com/datasets-zrbfhr74383/football-events.zip',
                              destfile=data.zip.file,
                              method="auto"),
                error=function(e) 1)
    unzip(data.zip.file, exdir=root)
}


ginf  <-  as_tibble(read_csv(ginf.file))

events <- as_tibble(read_csv(events.file))
events <- events %>%
              inner_join(ginf)
```



```{r}

events$event_type <- factor(events$event_type, levels=c(0,1,2,3,4,5,6,7,8,9,10,11), labels=c('Annoucement', 'Attempt','Corner','Foul', 'Yellow Card', 'Second Yellow Card', 'Red Card', 'Substitution', 'Free kick won', 'Offside', 'Hand Ball', 'Penalty Conceded'))

events$is_goal <- factor(events$is_goal, levels=c(0,1), labels=c('No Goal', 'Goal'))

events$shot_place <- factor(events$shot_place, levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13), labels=c('Bit Too High', 'Blocked', 'Bottom Left Corner', 'Bottom Right Corner', 'Centre Of Goal', 'High And Wide', 'Hits The Bar', 'Misses To The left', 'Misses To The Right', 'Too high', 'Top Centre Of The Goal', 'Top Left Corner', 'Top Right Corner'))

events$sixth <- cut(events$time,breaks = c(0, 15,30,45,60,75,90,120), labels = c('0-15','15-30','30-45', '45-60', '60-75', '75-90', '90-'))
events$bodypart <- factor(events$bodypart, levels=c(1,2,3), labels=c('Right Foot', 'Left Foot', 'Head'))

events$location <- factor(events$location, levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19), labels=c('Attacking half', 'Defense half', 'Centre of the box', 'Left wing', 'right wing', 'difficult angle and long range', 'difficult angle on the left', 'difficult angle on the right', 'Left Site Of The box',  'Left Site Of The Six Yard Box',  'Right Site Of The Box',  'Right Site Of The Six Yard Box', 'Very close range', 'Penalty Spot', 'Outsite The Box', 'long range', 'More Than 35 yards', 'More than 40 yards', 'not recorded'))

events$shot_outcome <- factor(events$shot_outcome, levels=c(1,2,3,4), labels=c('On target', 'off target', 'blocked', 'hit the bar'))

events$event_type2 <- factor(events$event_type2, levels=c(12,13,14,15), labels=c('Key pass', 'Failed Through ball', 'Sending Off', 'Own Goal'))

events$side <- factor(events$side, levels=c(1,2), labels=c('Home', 'Away'))

events$assist_method <- factor(events$assist_method, levels=c(0,1,2,3,4), labels=c('None', 'Pass','Cross', 'Headed Pass', 'Through Ball'))


events$situation <- factor(events$situation, levels=c(1,2,3,4), labels=c('Open Play', 'Set Piece','Corner', 'Free Kick'))

```



```{r}
players <- events %>%
  filter(event_type == 'Attempt') %>%
  select(player, is_goal, country) %>%
  na.omit() %>%
  group_by(player, country) %>%
  mutate(num_attempts=n()) %>%
  filter(is_goal == 'Goal') %>%
  group_by(player, country, num_attempts) %>%
  summarize(num_goals=n()) %>%
  mutate(goal_attempt_ratio=round(num_goals/num_attempts  * 100,1)) 
```


1. Preface
----------------


Millions of people are fascinated about football worldwide. 


2. Goals
--------


### 2.1 Positions ###


3. Top Attackers
----------------


```{r}

players %>%
  ggplot(aes(x=num_goals, y=num_attempts)) +
  geom_point(aes(color=country),stat='identity', size=4) + 
  geom_text(aes(label=player), hjust=0.5,vjust=-0.6, size=8) +
  scale_x_continuous(limit=c(73,205), breaks = seq(0,500,5)) +
  scale_y_continuous(limit=c(400,1210), breaks=seq(0,2000,50)) +
  labs(x='Number of Goals', y='Number Of Attempts', colour='Country', title='Total number of goals/number of attempts of top players across european top leagues 2011-2017') +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"), axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),  plot.title=element_text(size=20, face='bold'))


top_goalgetters <-(players %>%
  filter(num_goals > 72 & num_attempts > 400))$player


```



```{r}
assisting_players <- events %>%
  filter(event_type == 'Attempt') %>%
  select(player2, is_goal, country) %>%
  na.omit() %>%
  group_by(player2, country) %>%
  mutate(num_created_attempts=n()) %>%
  filter(is_goal == 'Goal') %>%
  group_by(player2, country, num_created_attempts) %>%
  summarize(num_goals=n()) %>%
  mutate(goal_attempt_ratio=round(num_goals/num_created_attempts  * 100,1)) 
```





```{r}

assisting_players %>%
  ggplot(aes(x=num_goals, y=num_created_attempts)) +
  geom_point(aes(color=country),stat='identity') + 
  geom_text(aes(label=player2), hjust=0.5,vjust=-0.6, size=8) +
  scale_x_continuous(limit=c(33,77), breaks = seq(0,100,5)) +
  scale_y_continuous(limit=c(310,420), breaks=seq(0,500,20)) +
  labs(y='Number of assisted attempts', x='Number of assisted goals', colour='Country', size='Number Of Attempts', title='Total number of assisted Attemps/assisted goals of top players across european top leagues 2011-2017') +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"), axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),  plot.title=element_text(size=20, face='bold'))

top_assists <-(assisting_players %>%
  filter(num_goals > 32 & num_created_attempts > 310))$player2

```


```{r}
top_attackers <- c(as.character(top_goalgetters), as.character(top_assists))
top_attackers
```



